# Generated by Django 3.0.2 on 2020-07-12 20:17

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Counter',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CounterItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date')),
                ('count', models.IntegerField(default=0)),
                ('counter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='people_counter.Counter')),
            ],
            options={
                'verbose_name': 'Counter Item',
                'ordering': ['-date'],
            },
        ),
    ]
